apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "2.7.4"
  interval: 5m
  timeout: 5m
  targetNamespace: kube-system
  values:
    # Custom values for the sealed-secrets Helm chart can go here
    # Example:
    # image:
    #   tag: "v0.16.0"
